# Generated by Django 3.0.5 on 2020-04-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=50)),
                ('Capital', models.BooleanField(default=False)),
                ('Date', models.CharField(blank=True, max_length=15)),
                ('FY', models.CharField(choices=[('2018', '2018'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024')], default='', max_length=50)),
                ('Category', models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing'), ('Meeting', 'Meeting'), ('Admin', 'Admin'), ('Fees', 'Fees'), ('Lawyer', 'Lawyer'), ('Marketing', 'Marketing'), ('Store', 'Store'), ('Brokage', 'Brokage'), ('Travel', 'Travel'), ('Bank Statement', 'Bank Statement')], default='', max_length=50)),
                ('Image', models.FileField(blank=True, unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Farhan',
            fields=[
                ('expenses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExpenseApp.Expenses')),
            ],
            bases=('ExpenseApp.expenses',),
        ),
        migrations.CreateModel(
            name='FarhanFamily',
            fields=[
                ('expenses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExpenseApp.Expenses')),
            ],
            bases=('ExpenseApp.expenses',),
        ),
        migrations.CreateModel(
            name='Nadia',
            fields=[
                ('expenses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExpenseApp.Expenses')),
            ],
            bases=('ExpenseApp.expenses',),
        ),
        migrations.CreateModel(
            name='Ongie',
            fields=[
                ('expenses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExpenseApp.Expenses')),
            ],
            bases=('ExpenseApp.expenses',),
        ),
        migrations.CreateModel(
            name='Orange',
            fields=[
                ('expenses_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExpenseApp.Expenses')),
            ],
            bases=('ExpenseApp.expenses',),
        ),
    ]
