# Generated by Django 3.0.5 on 2020-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
